import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { Header } from "@/components/Header/header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className={styles.main}>
        <div style={{ display: "flex" }}>
          <div className={styles.block}>
            <div className={`${styles.block_circle} ${styles.pink}`}></div>
          </div>
          <div className={styles.block}>
            <div className={`${styles.block_circle} ${styles.blue}`}></div>
          </div>
          <div className={styles.block}>
            <div className={styles.number}>1</div>
          </div>
          <div className={styles.block}>
            <div className={styles.number}>10</div>
          </div>
          <div className={styles.block}>
            <div className={styles.kana}>ア</div>
          </div>
        </div>
      </main>
    </>
  );
}
